export const GET_COURSES_SUCCESS = 'GET_COURSES_SUCCESS';

export const CREATE_COURSE = 'CREATE_COURSE';
export const CREATE_COURSE_SUCCESS = "CREATE_COURSE_SUCCESS";
export const UPDATE_COURSE_SUCCESS = "UPDATE_COURSE_SUCCESS";

export const GET_AUTHORS_SUCCESS = 'GET_AUTHORS_SUCCESS';